/**
 * Regions seed — idempotent loader for `prisma/seeds/data/regions.json`.
 *
 *   npm run seed:regions
 *   npm run seed:regions -- --types=country,city          # filter by type
 *   npm run seed:regions -- --dry-run                     # parse + log, do not write
 *
 * Two-pass strategy preserves FK integrity:
 *   Pass 1 — upsert regions in topological order (country → province → city →
 *            district → place_of_study). Original IDs are preserved so
 *            `universities.city_id` (Phase 17) keeps stable references.
 *   Pass 2 — upsert translations by (region_id, locale). If only `ru` is
 *            present for a region, the row is duplicated into `kk` (and
 *            vice-versa) so the KZ-only admin always finds a `kk` title.
 *
 * Source: `prisma/seeds/data/regions.json` — generated by `scripts/dump-geonline-regions.ts`.
 * If the file is missing, the seed prints a friendly message and exits 0
 * (so CI doesn't fail before the dump has been run in a fresh environment).
 */

import * as fs from 'fs';
import * as path from 'path';
import { PrismaClient, RegionType } from '../../generated/prisma';

const prisma = new PrismaClient();

const TYPE_ORDER: RegionType[] = ['country', 'province', 'city', 'district', 'place_of_study'];

interface SourceRegion {
    id: number;
    country_id: number | null;
    province_id: number | null;
    city_id: number | null;
    district_id: number | null;
    type: RegionType;
    created_at: number;
}

interface SourceTranslation {
    id: number;
    region_id: number;
    locale: string | null;
    title: string | null;
}

interface DumpFile {
    dumped_at: number;
    source_host: string;
    source_db: string;
    regions: SourceRegion[];
    translations: SourceTranslation[];
}

function parseArgs(argv: string[]): { types: Set<RegionType> | null; dryRun: boolean } {
    let types: Set<RegionType> | null = null;
    let dryRun = false;
    for (const arg of argv.slice(2)) {
        if (arg === '--dry-run') {
            dryRun = true;
        } else if (arg.startsWith('--types=')) {
            const list = arg.slice('--types='.length).split(',').map((s) => s.trim()).filter(Boolean);
            const invalid = list.filter((t) => !TYPE_ORDER.includes(t as RegionType));
            if (invalid.length) {
                throw new Error(`Unknown region type(s): ${invalid.join(', ')}`);
            }
            types = new Set(list as RegionType[]);
        }
    }
    return { types, dryRun };
}

function chunk<T>(arr: T[], size: number): T[][] {
    const out: T[][] = [];
    for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
    return out;
}

async function main(): Promise<void> {
    const { types, dryRun } = parseArgs(process.argv);
    const dataPath = path.resolve(__dirname, 'data', 'regions.json');

    if (!fs.existsSync(dataPath)) {
        console.log(`No regions dump at ${dataPath} — run \`npm run dump:regions\` first.`);
        return;
    }

    const raw = fs.readFileSync(dataPath, 'utf8');
    const dump: DumpFile = JSON.parse(raw);
    console.log(`Loaded ${dump.regions.length} regions + ${dump.translations.length} translations`);
    console.log(`  source: ${dump.source_host}/${dump.source_db}, dumped_at=${dump.dumped_at}`);

    // Filter by --types if provided. We always include ancestors so FKs stay valid.
    let regions = dump.regions;
    if (types) {
        const keepIds = new Set<number>();
        const byId = new Map(dump.regions.map((r) => [r.id, r] as const));
        const queue: SourceRegion[] = dump.regions.filter((r) => types.has(r.type));
        while (queue.length) {
            const r = queue.shift()!;
            if (keepIds.has(r.id)) continue;
            keepIds.add(r.id);
            for (const parentId of [r.country_id, r.province_id, r.city_id, r.district_id]) {
                if (parentId !== null && !keepIds.has(parentId)) {
                    const parent = byId.get(parentId);
                    if (parent) queue.push(parent);
                }
            }
        }
        regions = dump.regions.filter((r) => keepIds.has(r.id));
        console.log(`  after --types filter: ${regions.length} regions (including transitive ancestors)`);
    }

    // Group by type for topological insert order.
    const byType = new Map<RegionType, SourceRegion[]>();
    for (const t of TYPE_ORDER) byType.set(t, []);
    for (const r of regions) byType.get(r.type)!.push(r);

    if (dryRun) {
        for (const t of TYPE_ORDER) {
            console.log(`  ${t}: ${byType.get(t)!.length}`);
        }
        const localeCounts = new Map<string, number>();
        for (const tr of dump.translations) {
            const key = tr.locale ?? '(null)';
            localeCounts.set(key, (localeCounts.get(key) ?? 0) + 1);
        }
        console.log('  translations by locale:', Object.fromEntries(localeCounts));
        console.log('DRY RUN — no writes performed.');
        return;
    }

    // Pass 1 — regions, in topological order.
    for (const t of TYPE_ORDER) {
        const group = byType.get(t)!;
        if (!group.length) continue;
        let touched = 0;
        for (const batch of chunk(group, 500)) {
            await prisma.$transaction(
                batch.map((r) =>
                    prisma.region.upsert({
                        where: { id: r.id },
                        create: {
                            id: r.id,
                            type: r.type,
                            country_id: r.country_id,
                            province_id: r.province_id,
                            city_id: r.city_id,
                            district_id: r.district_id,
                            created_at: r.created_at || Math.floor(Date.now() / 1000),
                        },
                        update: {
                            type: r.type,
                            country_id: r.country_id,
                            province_id: r.province_id,
                            city_id: r.city_id,
                            district_id: r.district_id,
                        },
                    }),
                ),
            );
            touched += batch.length;
        }
        console.log(`  pass1 ${t}: ${touched}`);
    }

    // Pass 2 — translations. Group by region_id so we can fill missing locales.
    const keepRegionIds = new Set(regions.map((r) => r.id));
    const byRegion = new Map<number, SourceTranslation[]>();
    for (const tr of dump.translations) {
        if (!keepRegionIds.has(tr.region_id)) continue;
        if (!tr.locale || !tr.title) continue;
        const list = byRegion.get(tr.region_id) ?? [];
        list.push(tr);
        byRegion.set(tr.region_id, list);
    }

    // Normalize locale aliases: 'kk' is canonical; the source sometimes uses 'kz'.
    const canonicalize = (loc: string): string => (loc === 'kz' ? 'kk' : loc);

    let trTouched = 0;
    const upserts: { region_id: number; locale: string; title: string }[] = [];
    for (const [regionId, list] of byRegion.entries()) {
        const merged = new Map<string, string>();
        for (const tr of list) {
            const loc = canonicalize(tr.locale!);
            // First-wins per locale.
            if (!merged.has(loc)) merged.set(loc, tr.title!);
        }
        // Ensure 'kk' exists — KZ-only admin reads this. Fall back to 'ru' or any.
        if (!merged.has('kk')) {
            const fallback = merged.get('ru') ?? merged.values().next().value;
            if (fallback) merged.set('kk', fallback);
        }
        for (const [locale, title] of merged.entries()) {
            upserts.push({ region_id: regionId, locale, title });
        }
    }

    for (const batch of chunk(upserts, 500)) {
        await prisma.$transaction(
            batch.map((u) =>
                prisma.regionTranslation.upsert({
                    where: { region_id_locale: { region_id: u.region_id, locale: u.locale } },
                    create: { region_id: u.region_id, locale: u.locale, title: u.title },
                    update: { title: u.title },
                }),
            ),
        );
        trTouched += batch.length;
    }
    console.log(`  pass2 translations: ${trTouched}`);

    console.log('Done.');
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
